services:
  web:
    image: 312103758391.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DEBUG=1